name: Trigger auto deployment for container-app-2rmmtb4qe6pgy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-2rmmtb4qe6pgy-AutoDeployTrigger-4b3cd3d5-3a80-4639-8976-93aa1fe01dca.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP2RMMTB4QE6PGY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP2RMMTB4QE6PGY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP2RMMTB4QE6PGY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP2RMMTB4QE6PGY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP2RMMTB4QE6PGY_REGISTRY_PASSWORD }}
          containerAppName: container-app-2rmmtb4qe6pgy
          resourceGroup: appspacesragappb0ba8b2e
          imageToBuild: default/container-app-2rmmtb4qe6pgy:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


